export const HANDLE_POP_UP = "HANDLE_POP_UP";
export const HANDLE_EDGE_CLICK = "HANDLE_EDGE_CLICK";
export const HANDLE_COMPONENT_RENDER = "HANDLE_COMPONENT_RENDER";
export const INITIAL_ELEMENTS = "INITIAL_ELEMENTS";
export const SET_NODES = "SET_NODES";
